"""second

Revision ID: 6a3a591b4026
Revises: ab27394e52ad
Create Date: 2020-06-07 18:57:42.634615

"""

# revision identifiers, used by Alembic.
revision = '6a3a591b4026'
down_revision = 'ab27394e52ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
