"""xxx

Revision ID: f6274c0b46e8
Revises: 6a3a591b4026
Create Date: 2020-06-07 19:06:22.536162

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f6274c0b46e8'
down_revision = '6a3a591b4026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_parent_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'posts', ['parent_id'], ['post_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_parent_id_fkey', 'posts', 'posts', ['parent_id'], ['post_id'])
    # ### end Alembic commands ###
